const express=require('express');
const http=require('http');
const crypto=require('crypto');
const cookie=require('cookie');
const WebSocket=require('ws');
const path=require('path');
const app=express(); const server=http.createServer(app); const wss=new WebSocket.Server({server});
const PORT=process.env.PORT||3000, BASE_URL=process.env.BASE_URL||`http://localhost:${PORT}`;
const SESSION_TTL=30*24*60*60*1000, STATE_TTL=10*60*1000, COOKIE='__Host-otti_session';
const sessions=new Map(), users=new Map(), states=new Map(), rooms=new Map(), sockets=new Set(), members=new Map();
const GOOGLE_CLIENT_ID=process.env.GOOGLE_CLIENT_ID||'', GOOGLE_CLIENT_SECRET=process.env.GOOGLE_CLIENT_SECRET||'';
const GITHUB_CLIENT_ID=process.env.GITHUB_CLIENT_ID||'', GITHUB_CLIENT_SECRET=process.env.GITHUB_CLIENT_SECRET||'';
app.use(express.json({limit:'32kb'})); app.use(express.static(path.join(__dirname,'public')));
const clean=(v,f='')=>String(v??f).replace(/\s+/g,' ').trim(); const rid=()=>crypto.randomUUID();
const hash=v=>crypto.createHash('sha256').update(v).digest('hex'); const secret=()=>crypto.randomBytes(32).toString('base64url');
function setCookie(res,v,maxAge=2592000){res.setHeader('Set-Cookie',cookie.serialize(COOKIE,v,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',path:'/',maxAge}));}
function session(req){const c=cookie.parse(req.headers.cookie||'')[COOKIE]; if(!c)return null; const s=sessions.get(hash(c)); if(!s||s.expires<Date.now()){if(s)sessions.delete(hash(c));return null} return s;}
function user(req){const s=session(req);return s?users.get(s.userId)||null:null}
function startSession(uid){const raw=secret();sessions.set(hash(raw),{userId:uid,expires:Date.now()+SESSION_TTL});return raw}
function finishSession(req,res){const c=cookie.parse(req.headers.cookie||'')[COOKIE];if(c)sessions.delete(hash(c));setCookie(res,'',-1)}
function requireAuth(req,res,next){const u=user(req);if(!u)return res.status(401).json({error:'AUTH_REQUIRED'});req.user=u;next()}
function ensureUser(provider,pid,p){const k=provider+':'+pid;let u=users.get(k);if(!u){u={id:rid(),provider,providerId:pid,email:p.email||null,name:clean(p.name||'Otti User').slice(0,60),avatar:p.avatar||null};users.set(k,u)}return u}
function room(id){if(!rooms.has(id))rooms.set(id,{messages:[],clients:new Set()});return rooms.get(id)}
function allowed(uid,r){if(!members.has(r)){members.set(r,new Set([uid]));return true}return members.get(r).has(uid)}
function send(ws,x){if(ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify(x))} function broadcast(r,x,except){for(const w of r.clients)if(w!==except)send(w,x)}
app.get('/api/auth/me',(req,res)=>{const u=user(req);res.json({authenticated:!!u,user:u?{id:u.id,email:u.email,name:u.name,avatar:u.avatar}:null})});
app.get('/api/auth/config',(req,res)=>res.json({google:!!GOOGLE_CLIENT_ID,github:!!GITHUB_CLIENT_ID,email:true}));
app.post('/api/auth/demo-email',(req,res)=>{const email=clean(req.body?.email).toLowerCase();if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email))return res.status(400).json({error:'INVALID_EMAIL'});const u=ensureUser('email',email,{email,name:email.split('@')[0]});setCookie(res,startSession(u.id));res.json({ok:true,user:{id:u.id,email:u.email,name:u.name}})});
app.post('/api/auth/logout',(req,res)=>{finishSession(req,res);res.json({ok:true})});
function state(provider){const s=secret();states.set(s,{provider,expires:Date.now()+STATE_TTL});return s} function takeState(s,p){const x=states.get(s);states.delete(s);return x&&x.provider===p&&x.expires>Date.now()}
app.get('/auth/google',(req,res)=>{if(!GOOGLE_CLIENT_ID||!GOOGLE_CLIENT_SECRET)return res.status(503).send('Google OAuth is not configured.');const s=state('google');const u=new URL('https://accounts.google.com/o/oauth2/v2/auth');u.searchParams.set('client_id',GOOGLE_CLIENT_ID);u.searchParams.set('redirect_uri',`${BASE_URL}/auth/google/callback`);u.searchParams.set('response_type','code');u.searchParams.set('scope','openid email profile');u.searchParams.set('state',s);res.redirect(u.toString())});
app.get('/auth/google/callback',async(req,res)=>{try{if(!takeState(req.query.state,'google'))return res.status(400).send('Invalid OAuth state.');const b=new URLSearchParams({code:req.query.code,client_id:GOOGLE_CLIENT_ID,client_secret:GOOGLE_CLIENT_SECRET,redirect_uri:`${BASE_URL}/auth/google/callback`,grant_type:'authorization_code'});const t=await (await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:b})).json();const p=await (await fetch('https://openidconnect.googleapis.com/v1/userinfo',{headers:{Authorization:`Bearer ${t.access_token}`}})).json();const u=ensureUser('google',p.sub,{email:p.email,name:p.name,avatar:p.picture});setCookie(res,startSession(u.id));res.redirect('/')}catch(e){res.status(500).send('Google sign-in failed.')}});
app.get('/auth/github',(req,res)=>{if(!GITHUB_CLIENT_ID||!GITHUB_CLIENT_SECRET)return res.status(503).send('GitHub OAuth is not configured.');const s=state('github');const u=new URL('https://github.com/login/oauth/authorize');u.searchParams.set('client_id',GITHUB_CLIENT_ID);u.searchParams.set('redirect_uri',`${BASE_URL}/auth/github/callback`);u.searchParams.set('scope','read:user user:email');u.searchParams.set('state',s);res.redirect(u.toString())});
app.get('/auth/github/callback',async(req,res)=>{try{if(!takeState(req.query.state,'github'))return res.status(400).send('Invalid OAuth state.');const b=new URLSearchParams({client_id:GITHUB_CLIENT_ID,client_secret:GITHUB_CLIENT_SECRET,code:req.query.code,redirect_uri:`${BASE_URL}/auth/github/callback`});const t=await (await fetch('https://github.com/login/oauth/access_token',{method:'POST',headers:{Accept:'application/json','Content-Type':'application/x-www-form-urlencoded'},body:b})).json();const p=await (await fetch('https://api.github.com/user',{headers:{Authorization:`Bearer ${t.access_token}`,Accept:'application/vnd.github+json','User-Agent':'Otti'}})).json();let email=p.email;if(!email){const es=await (await fetch('https://api.github.com/user/emails',{headers:{Authorization:`Bearer ${t.access_token}`,Accept:'application/vnd.github+json','User-Agent':'Otti'}})).json();email=es.find(x=>x.primary&&x.verified)?.email||es.find(x=>x.verified)?.email}const u=ensureUser('github',String(p.id),{email,name:p.name||p.login,avatar:p.avatar_url});setCookie(res,startSession(u.id));res.redirect('/')}catch(e){res.status(500).send('GitHub sign-in failed.')}});
app.get('/api/conversations/:room/access',requireAuth,(req,res)=>{const r=clean(req.params.room).slice(0,80);res.json({allowed:allowed(req.user.id,r),room:r})});
app.get('/health',(req,res)=>res.json({ok:true,service:'otti-auth-v1',users:users.size,sessions:sessions.size,rooms:rooms.size,connections:sockets.size}));
wss.on('connection',(ws,req)=>{sockets.add(ws);const c=cookie.parse(req.headers.cookie||'')[COOKIE];const s=c?sessions.get(hash(c)):null;ws.authUserId=s&&s.expires>Date.now()?s.userId:null;ws.meta={roomId:null,userId:null,name:null};
ws.on('message',raw=>{let d;try{d=JSON.parse(raw)}catch{return send(ws,{type:'error',message:'Invalid message.'})}if(d.type==='join'){if(!ws.authUserId)return send(ws,{type:'auth_required'});const u=users.get(ws.authUserId),r=clean(d.roomId,'general').slice(0,80);if(!u||!allowed(u.id,r))return send(ws,{type:'forbidden',message:'Conversation access denied.'});if(ws.meta.roomId)room(ws.meta.roomId).clients.delete(ws);const x=room(r);x.clients.add(ws);ws.meta={roomId:r,userId:u.id,name:u.name};return send(ws,{type:'joined',room:r,userId:u.id,name:u.name,messages:x.messages,online:[...x.clients].map(q=>q.meta)})}if(!ws.meta.roomId)return send(ws,{type:'error',message:'Join a room first.'});const x=room(ws.meta.roomId);if(d.type==='message'){const text=clean(d.text).slice(0,2000);if(!text)return;const m={id:rid(),room:ws.meta.roomId,userId:ws.meta.userId,name:ws.meta.name,text,createdAt:new Date().toISOString(),reactions:{}};x.messages.push(m);if(x.messages.length>1000)x.messages.shift();return broadcast(x,{type:'message',message:m})}if(d.type==='typing')return broadcast(x,{type:'typing',userId:ws.meta.userId,name:ws.meta.name,typing:!!d.typing},ws);if(d.type==='dive')return broadcast(x,{type:'dive',userId:ws.meta.userId,name:ws.meta.name,active:!!d.active},ws);});
ws.on('close',()=>{sockets.delete(ws);if(ws.meta.roomId)room(ws.meta.roomId).clients.delete(ws)})});
server.listen(PORT,()=>console.log(`Otti Auth V1 on ${PORT}`));
